<div class="row mt-5">

<div class="col-lg-6 col-6 p-2">
{% if next_post %}
<a 
href="{{ next_post.url }}">
{% if next_post.image %}<img class="img-post mb-3" 
width="100%" height="100%"
alt="{{next_post.title}}"
src="{{next_post.image  or metadata.image}}"
/>{% endif %}
<div class="p-3">
<h3>{{ next_post.title }}</h3>
<p>{{ next_post.description }}</p>
</div>
</a>
{% endif %}
</div>

<div class="col-lg-6 col-6 p-2">
{% if prev_post %}
<a 
href="{{ prev_post.url }}">
{% if prev_post.image %}<img class="img-post mb-3" 
width="100%" height="100%"
alt="{{prev_post.title}}"
src="{{prev_post.image or metadata.image}}"
/>{% endif %}
<div class="p-3 text-end">
<h3>{{ prev_post.title }}</h3>
{{ prev_post.description }}
</a>
</div>
{% endif %}
</div>
</div>